--CREATE DATABASE SCRIPT
-- Database: EMS

-- DROP DATABASE "EMS";

CREATE DATABASE "EMS"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Turkish_Turkey.1254'
    LC_CTYPE = 'Turkish_Turkey.1254'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
--CREATE TABLE SCRIPTS
--organizator	
-- Table: public.organizator

-- DROP TABLE public.organizator;

CREATE TABLE public.organizator
(
    organizator_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Organizator_pkey" PRIMARY KEY (organizator_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.organizator
    OWNER to postgres;
	

--category
-- Table: public.category

-- DROP TABLE public.category;

CREATE TABLE public.category
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Category_pkey" PRIMARY KEY (category_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.category
    OWNER to postgres;

--events
-- Table: public.events

-- DROP TABLE public.events;

CREATE TABLE public.events
(
    event_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    county character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    city character varying COLLATE pg_catalog."default" NOT NULL,
    quota character varying COLLATE pg_catalog."default" NOT NULL,
    category_id integer NOT NULL,
    discount_rate integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    camping_info character varying COLLATE pg_catalog."default",
    organizator_id integer,
    total_participation integer,
    CONSTRAINT "Event_pkey" PRIMARY KEY (event_id),
    CONSTRAINT "Event_to_Category" FOREIGN KEY (category_id)
        REFERENCES public.category (category_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Event_to_Organizator" FOREIGN KEY (organizator_id)
        REFERENCES public.organizator (organizator_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.events
    OWNER to postgres;

-- Index: fki_Event_to_Category

-- DROP INDEX public."fki_Event_to_Category";

CREATE INDEX "fki_Event_to_Category"
    ON public.events USING btree
    (category_id)
    TABLESPACE pg_default;

-- Index: fki_Event_to_Organizator

-- DROP INDEX public."fki_Event_to_Organizator";

CREATE INDEX "fki_Event_to_Organizator"
    ON public.events USING btree
    (organizator_id)
    TABLESPACE pg_default;	
	
--invoice	
-- Table: public.invoice

-- DROP TABLE public.invoice;

CREATE TABLE public.invoice
(
    invoice_id integer NOT NULL,
    event_name character varying COLLATE pg_catalog."default" NOT NULL,
    location character varying COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    amount_of_payment integer NOT NULL,
    CONSTRAINT "Invoice_pkey" PRIMARY KEY (invoice_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.invoice
    OWNER to postgres;
	

--users
-- Table: public.users

-- DROP TABLE public.users;

CREATE TABLE public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    surname character varying COLLATE pg_catalog."default" NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    mail character varying COLLATE pg_catalog."default" NOT NULL,
    birthdate date NOT NULL,
    event_id integer,
    membership_type character varying COLLATE pg_catalog."default" NOT NULL,
    invoice_id integer,
    participated_events integer,
    total_paid integer,
    CONSTRAINT "User_pkey" PRIMARY KEY (user_id),
    CONSTRAINT "User_to_Event" FOREIGN KEY (event_id)
        REFERENCES public.events (event_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "User_to_Invoice" FOREIGN KEY (invoice_id)
        REFERENCES public.invoice (invoice_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;

-- Index: fki_User_to_Event

-- DROP INDEX public."fki_User_to_Event";

CREATE INDEX "fki_User_to_Event"
    ON public.users USING btree
    (event_id)
    TABLESPACE pg_default;

-- Index: fki_User_to_Invoice

-- DROP INDEX public."fki_User_to_Invoice";

CREATE INDEX "fki_User_to_Invoice"
    ON public.users USING btree
    (invoice_id)
    TABLESPACE pg_default;
	
--INSERT SCRIPTS
--category

INSERT INTO category (name) VALUES
    ('Concert');

INSERT INTO category (name) VALUES
    ('Tour');

INSERT INTO category (name) VALUES
    ('Historic Trip');

INSERT INTO category (name) VALUES
    ('Academic');

--organizator

INSERT INTO organizator (username,password,name) VALUES
    ('jj','jj123','Jolly Joker');

INSERT INTO organizator (username,password,name) VALUES
    ('vv','v987','Volume');

INSERT INTO organizator (username,password,name) VALUES
    ('ovenue','oven425','Ooze Venue');

INSERT INTO organizator (username,password,name) VALUES
    ('bio','b257','Bios');

INSERT INTO organizator (username,password,name) VALUES
    ('D_Eylul_uni','deu78','Dokuz Eylül University');
	
INSERT INTO organizator (username,password,name) VALUES
    ('Middle_east_tec_uni','mt06','METU');


--events

INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Concert of Skillet','Çeşme','...','İzmir','100','1','0','2019-10-15','2019-10-16','Jolly Joker Alaçatı','90','0','10');

INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Concert of INNA','Alsancak ','...','İzmir','80','0','0','2019-9-12','2019-9-13',' Volume Alsancak','70','1','1');

INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Concert of INNA','Bornova ','...','İzmir','80','0','0','2019-4-12','2019-4-13',' Ooze Venue','70','2','2');

INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Concert of Skrillex','Konak','...','İzmir','100','0','0','2019-5-10','2019-5-11','Bios','125','3','5');


INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Bitcoin Seminar','Konak','...','İzmir','100','3','20','2019-5-19','2019-5-19','Dokuz Eylül University','0','4','7');

INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Get Ready To Business Life Seminar','Konak','...','İzmir','100','3','20','2019-5-20','2019-5-20','Dokuz Eylül University','500','4','15');
	
INSERT INTO events (name,county,description,city,quota,category_id,discount_rate,start_date,end_date,address,price,organizator_id,total_participation) VALUES
    ('Entrepreneurship Seminar','Çankaya','...','Ankara','100','3','20','2019-3-17','2019-3-17','METU','400','4','10');





--users

INSERT INTO users (name,surname,username,password,mail,birthdate,event_id,membership_type,participated_events,total_paid) VALUES ('Ahmet','Hakan','ah12','ahmet432','ahakan@gmail.com','1985-2-25','1','standart', '3','230');

INSERT INTO users (name,surname,username,password,mail,birthdate,event_id,membership_type,participated_events,total_paid) VALUES ('Cem','Yılmaz','cem12','cem35','cyilmaz@gmail.com','1975-3-30','1','standart', '0','0');

INSERT INTO users (name,surname,username,password,mail,birthdate,event_id,membership_type,participated_events,total_paid) VALUES ('Çağatay','Akman','ca12','cagatay78','cakman@gmail.com','2000-1-15','2','standart','5','355');


--SQL SCRIPTS
--QUERY1
SELECT * FROM events WHERE city='İzmir';
--QUERY2
SELECT price*total_participation AS highest_revenue,events.name,category.name,organizator.name FROM events
INNER JOIN category
ON events.category_id = category.category_id
INNER JOIN organizator
ON events.organizator_id = organizator.organizator_id
ORDER BY price*total_participation desc limit 1;
--QUERY3*
select count(category.name),category.name,events.name from category
INNER JOIN events
ON events.category_id = category.category_id
GROUP BY category.name,events.name
ORDER BY category.name desc;
--QUERY4*
SELECT * FROM events WHERE end_date<'2019-10-10';
--QUERY5
SELECT * FROM events WHERE end_date<'2019-10-10' AND total_participation < 3;
--QUERY6
UPDATE users SET membership_type='gold' WHERE participated_events >= 3;
--QUERY7
DELETE FROM events WHERE events.category_id = '3' AND address = 'Dokuz Eylül University' AND start_date = '2019-5-19';
--QUERY8
SELECT mail FROM users WHERE total_paid=(SELECT MAX(total_paid) FROM users);
--QUERY9
UPDATE events SET discount_rate = 25 WHERE city LIKE 'İ%';
--QUERY10
DELETE FROM users WHERE participated_events = 0;